'''
Project Euler Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''
import math

triangle = 1
count = 1
while True:
    count += 1
    triangle += count
    if not triangle % 2:
        factors = [(i, triangle / i) for i in range(1, int(math.sqrt(triangle)) + 1) if not triangle % i]
    else:
        factors = []
    if not count % 10:
	    print "Triangle %s (%s) has %s factors" % (count, triangle, len(factors))

    if len(factors) > 500:
		print "Found it!"
		print "Triangle %s (%s) has %s factors" % (count, triangle, len(factors))
		break
